---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-app
  template:
    metadata:
      labels:
        name: go-app
    spec:
      containers:
      - name: golang
        image: docker-go:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 80
