---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: php-app
  template:
    metadata:
      labels:
        name: php-app
    spec:
      containers:
      - name: php
        image: docker-php:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 80
